---
title: "MVE Blue Seeds"
author: "Brooke Wainwright"
format: html
editor: visual
---

## Background

The Sevilleta Long Term Ecological Research (LTER) Program (Socorro, NM) rolled out a novel climate change experiment in 2019: the Mean-Variance Experiment (MVE). The experiment has been replicated in four ecosystems to date but the focus of this document is on the experimental infrastructure found in the Great Plains Grassland ecosystem, dominated by blue grama grass (*Bouteloua gracilis*). Hence Mean-Variance Blue or MVE Blue. The ecosystem is dominated by blue grama grass but the adjacent ecosystem, Chihuahuan Desert Grassland, is dominated by black grama grass (*Bouteloua eriopoda*). Great Plains Grassland extends northward throughout central North America while Chihuahuan Desert Grassland extends southward into Mexico. Thus, under a more arid climate, we would expect Chihuahuan Desert Grassland to expand it's range northward. The experimental infrastructure is set near the ecotone of these two ecosystems. More information on this experiment can be found here: <https://sevlter.unm.edu/mean-variance-experiment/>. To test the recruitment dynamics of these dominant plants under climate change, we added seeds of each species to the experimental plots from 2019-2023 and tracked their germination and survival biweekly during the growing season and monthly during the dormant season.

## Objectives

1.  Bring in seed monitoring data for all five years, bring in keys, bring in soil moisture data, bring in climate data.
2.  Explore data provide summary statistics.
3.  Create graph of typical climate (last 5-6 years) for temperature and precipitation.
4.  Separate monitoring data into germination and survival.
5.  Find the best model for the germination data using year and mean and variance treatments as predictors
6.  Graph germination by year, mean, and variance.
7.  Find best model of survival by species, year, and mean and variance treatments. Or a model for each species. Graph.
8.  Figure out the 1-3 events each year where 90-95% of germination occurs and isolate germination and soil moisture to those events and build a model to understand how soil moisture determines germination probability. Graph.
9.  Characterize die off/survival. Is it gradual and consistent or happen in major events like germination. Graph?
10. Figure out how to test for legacy effects on germination and/or survival. Graph.

## Setup

Read in necessary packages.

```{r}
#| message: false
#| warning: false
#| echo: false

library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(viridis) # colorblind friendly color palette
```

## Read Data

## Data Exploration 

## Characterize Climate

## Germination & Survival (Separate)

## Simple model of germination using Year and Treatments

## Graph germination by year and treatments

## Model & Graph Survival

## Model Soil Moisture Germination Events

## Graph Soil Moisture Events

## Characterize Survival (Pulse or Press)

## Legacy Model & Graph
